### ISSUE TITLE
Configure oplog for purely reactive data source

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#45] opened 2018-01-02 18:46 UTC
Please do work for this task in a branch called issue-045.

The current Mongo database is not setup to provide reactive updates via its oplog. Mongo should be configured so that it creates and writes to an oplog. This oplog will then provide reactive data updates to OPQView, eliminating the need to constantly poll the DB.

**Comment by philipmjohnson** [comment] 2018-03-30 18:53
Duplicate of #92, which provides more detail.

**Closed by philipmjohnson** 2018-03-30 18:53 UTC
Labels: MongoDB
